title: Abou Bakr Essadiq REDJIL
description: 
theme: jekyll-theme-minimal

author:
  name: Abou Bakr Essadiq REDJIL
  github: aredjil
  linkedin: Abou-Bakr-Essadiq-REDJIL

header_pages:
  - index.md
  - about.md
  - _pages/projects.md
  - _pages/ideas.md
  - _pages/resume.md

include:
  - _pages
markdown: kramdown

kramdown:
  math_engine: mathjax