title: Abou Bakr Essadiq REDJIL
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme

markdown: kramdown
kramdown:
  math_engine: mathjax


author:
  name: Abou Bakr Essadiq REDJIL
  github: aredjil
  linkedin: Abou-Bakr-Essadiq-REDJIL

header_pages:
  - index.md
  - about.md
  - projects.md
  - ideas.md
  - resume.md

include:
  - _pages
  