title: Abou Bakr Essadiq REDJIL
description: 
theme: jekyll-theme-minimal
author:
  name: Abou Bakr Essadiq REDJIL
  github: aredjil
  linkedin: 

header_pages:
  - index.md
  - about.md
  - projects.md
