title: Abou Bakr Essadiq REDJIL
description: My personal website
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme

include:
  - _pages

header_pages:
  - index.md
  - _pages/about.md
  - _pages/projects.md
  - _pages/ideas.md
  - _pages/reading.md
  - _pages/resume.md
