title: Abou Bakr Essadiq REDJIL
description: 
theme: jekyll-theme-minimal
author:
  name: Abou Bakr Essadiq REDJIL
  github: aredjil
  linkedin: Abou-Bakr-Essadiq-REDJIL

header_pages:
  - _pages/index.md
  - _pages/about.md
  - _pages/ projects.md
  - _pages/ideas.md
