title: Abou Bakr Essadiq REDJIL
description: My personal website
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme

markdown: kramdown
kramdown:
  math_engine: mathjax

include:
  - _pages

header_pages:
  - index.md
  - about.md
  - projects.md
  - ideas.md
  - resume.md
