title: Abou Bakr Essadiq REDJIL
description: 
theme: jekyll-theme-minimal
author:
  name: Abou Bakr Essadiq REDJIL
  github: aredjil
  linkedin: Abou-Bakr-Essadiq-REDJIL

header_pages:
  - _pages/index.mdindex.md
  - about.md
  - projects.md
  - ideas.md
